# Generated by Django 3.2 on 2021-11-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('app_type', models.CharField(choices=[('wordpress', 'Wordpress'), ('magento', 'Magento')], default='wordpress', max_length=20)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='buckets.bucket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
